export const SET_LOADING = 'SET_LOADING';
export const ADD_SCHEDULE_DATA = 'ADD_SCHEDULE_DATA';
export const CHANGE_LECTURE_STATUS = 'CHANGE_LECTURE_STATUS';
export const CHANGE_PRACTICAL_STATUS = 'CHANGE_PRACTICAL_STATUS';
export const CHANGE_SELECTED_PRACTICAL = 'CHANGE_SELECTED_PRACTICAL';
export const SET_PROGRAMMES = 'SET_PROGRAMMES';
export const SET_SELECTED_PROGRAMME = 'SET_SELECTED_PROGRAMME';
export const CHANGE_COURSE_ENABLED = 'CHANGE_COURSE_ENABLED';
