export const ADD_SCHEDULE_DATA = 'ADD_SCHEDULE_DATA';
export const CHANGE_LECTURE_STATUS = 'CHANGE_LECTURE_STATUS';
export const CHANGE_PRACTICAL_STATUS = 'CHANGE_PRACTICAL_STATUS';
export const CHANGE_SELECTED_PRACTICAL = 'CHANGE_SELECTED_PRACTICAL';
